[workspace]

members = [
    "entrega1",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace.dependencies]
clap = { version = "4.1.8", features = ["derive"] }
